cookies:
  NAC: "otGKBYgFQJqg"
  NNB: "627SWJZ35YQGO"
  nid_inf: "184739191"
  NID_AUT: "W/Xv2i1jyBiG9Pqn4wKDJBbnmypDfWDrvEAg6a5RJVAJGpRaEPmP2LXSL31UUYH7"
  NID_JKL: "p/3QoadrEM0oU/5i8q2Ay7jqxlJRDfM+EHAlBwsvv/o="
  "ba.uuid": "7ec8cd3d-fbef-403b-b03e-9ef8c95eb876"
  "nhn.realestate.article.trade_type_cd": ""
  "nhn.realestate.article.ipaddress_city": "3000000000"
  _fwb: "186OA0mYbJ3K9sB2W67kDiZ.1732177776292"
  landHomeFlashUseYn: "Y"
  "realestate.beta.lastclick.cortar": "3020000000"
  page_uid: "iz9uYdqo1e8ssSFVKZCssssstjK-166195"
  NACT: "1"
  NID_SES: "AAABvDhaz0s7UMEww+SeXsIjxQ9PIkwXe1hY0/91LjVtcnHLSOu9fVRRZ6BPWZH3HFi8B/CNw78rXBo9IqfFErdfxc9aG0GqCs4r/57BR0xgvZRgN2gq7rrJOzCgGIpk1EMV0n90+DaqR49HyabMLMpW4yvAOqG4o/afBJIRgIh8CfT7DUpA9DRcqwTWKjnQR3XQ8zsSwXvkwe/FivAob6PNTzY63RM5mWp9mn33rwwvQ+6FWXNS3Xho1fU6qOAF1gvpvpzJk5vGx5Y/t7xU4+1gGCw4lX7ZkMc7JYU5RSqnnvLtbZcEaNsX0n4VhgvGdu5alHKvIqMh1ZirC1rBkaZw51hC/mXUM9v/xoLzU1d4zYEFjTjz0rKPiabRToH8Ti172wAxlLzRszArbigNAEIMIXpeI+ZePjGGphhmcrMHygu+5yENZ3dxgVzOGQWB0e8Ca02Rtq4nGXOlKi12Fz4rQzdkXU7Is6bj1E45q6XdnQcrDR9cpQ1J9bdo4imuKjYV9QtG63/uo/jlfAZ0WvWZW8NUbQWNRNVeJ+IG8fEhT+HezXGfEm4sTh0e0zjNrYICoOfWmaj0uQiw4fa/UNuiCfI="
  "nhn.realestate.article.rlet_type_cd": "A01"
  REALESTATE: "Fri Nov 22 2024 14:14:48 GMT+0900 (Korean Standard Time)"
  wcs_bt: "4f99b5681ce60:1732252489"
  BUC: "PykcXEW9e0rNi3U1oRY0iKJCTQbNvp_zJ7zCNpqdAAg="