
authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IlJFQUxFU1RBVEUiLCJpYXQiOjE3MzIyNTI0ODgsImV4cCI6MTczMjI2MzI4OH0.FMjneFYGqgJYOF0RrR4PT00EBBEvLphzAae6IKU83mQ"
referer: "https://new.land.naver.com/"
user-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"